name: Boot Run Test

on:
  workflow_dispatch:

jobs:
  run-jar:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build
        shell: cmd
        run: mvn clean package

      - name: Run application
        shell: powershell
        run: |
          $p = Start-Process `
            -FilePath "java" `
            -ArgumentList "-Dspring.profiles.active=github", "-jar", "target\employee-api.war" `
            -RedirectStandardOutput "app.log" `
            -RedirectStandardError "app.err" `
            -PassThru

          $p.Id | Out-File app.pid -Encoding ascii
          Start-Sleep -Seconds 45

      - name: Show process status
        shell: powershell
        run: |
          if (Test-Path .\app.pid) {
            $pid = Get-Content .\app.pid
            $proc = Get-Process -Id $pid -ErrorAction SilentlyContinue
            if ($proc) {
              Write-Host "PROCESS ALIVE: PID=$pid"
            } else {
              Write-Host "PROCESS NOT RUNNING: PID=$pid"
            }
          } else {
            Write-Host "app.pid NOT FOUND"
          }

      - name: Show app.log
        shell: powershell
        run: |
          Write-Host "===== app.log ====="
          if (Test-Path .\app.log) {
            Get-Content .\app.log
          } else {
            Write-Host "app.log NOT FOUND"
          }

          Write-Host "===== app.err ====="
          if (Test-Path .\app.err) {
            Get-Content .\app.err
          } else {
            Write-Host "app.err NOT FOUND"
          }

      - name: Check 8080
        shell: powershell
        run: |
          $r = Test-NetConnection -ComputerName localhost -Port 8080
          $r

      - name: Check Application
        shell: cmd
        run: curl -v http://localhost:8080/