name: Boot Run Test

on:
  workflow_dispatch:

jobs:
  run-jar:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build
        shell: cmd
        run: mvn clean package

      - name: Run application (foreground)
        shell: cmd
        run: java -Dspring.profiles.active=github -jar target\employee-api.war