name: CD (Tomcat Deploy)

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build WAR
        run: mvn clean package

      - name: Download Tomcat
        shell: powershell
        run: |
          curl.exe -L -o tomcat.zip https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.36/bin/apache-tomcat-10.1.36-windows-x64.zip
          tar -xf tomcat.zip

      - name: Check extracted folders
        shell: powershell
        run: |
          Get-ChildItem
          Get-ChildItem apache-tomcat-10.1.36
          Get-ChildItem apache-tomcat-10.1.36\bin
          Get-ChildItem apache-tomcat-10.1.36\webapps

      - name: Deploy WAR to Tomcat
        shell: cmd
        run: copy target\employee-api.war apache-tomcat-10.1.36\webapps\

      - name: Start Tomcat
        shell: powershell
        run: |
          $tomcat = Join-Path $PWD "apache-tomcat-10.1.36"
          $stdout = Join-Path $PWD "tomcat-stdout.txt"
          $stderr = Join-Path $PWD "tomcat-stderr.txt"

          $env:CATALINA_HOME = $tomcat
          $env:CATALINA_BASE = $tomcat

          Start-Process `
            -FilePath "$tomcat\bin\catalina.bat" `
            -ArgumentList "run" `
            -WorkingDirectory $tomcat `
            -RedirectStandardOutput $stdout `
            -RedirectStandardError $stderr `
            -NoNewWindow

      - name: Wait for Tomcat
        shell: powershell
        run: Start-Sleep -Seconds 20

      - name: Show Tomcat output
        shell: powershell
        run: |
          Write-Host "=== tomcat-stdout.txt ==="
          if (Test-Path .\tomcat-stdout.txt) { Get-Content .\tomcat-stdout.txt } else { Write-Host "stdout file not found" }

          Write-Host "=== tomcat-stderr.txt ==="
          if (Test-Path .\tomcat-stderr.txt) { Get-Content .\tomcat-stderr.txt } else { Write-Host "stderr file not found" }

          Write-Host "=== logs directory ==="
          Get-ChildItem apache-tomcat-10.1.36\logs -ErrorAction SilentlyContinue

          $logFiles = Get-ChildItem apache-tomcat-10.1.36\logs\*.log -ErrorAction SilentlyContinue
          if ($logFiles) {
            Write-Host "=== Tomcat log contents ==="
            Get-Content $logFiles
          } else {
            Write-Host "No Tomcat log files found."
          }

      - name: Check port 8080
        shell: powershell
        run: |
          Test-NetConnection -ComputerName localhost -Port 8080

      - name: Check Application
        run: curl.exe http://localhost:8080/employee-api/